### ISSUE TITLE
create format that's "importable" by Confluence

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-generator#17]
(no, the current docx version cannot simply be imported due to issues with title formats...)

never mind - a user asked for a format that's can easily be imported into a Confluence
(their confluence-instance is administered by an external party and they don't have the rights
needed to space-import...)

**Comment by rdmueller** [comment]
docToolchain might be used in this case to write the template to a confluence space. It only needs write access of a standard user

**Comment by gernotstarke** [comment]
will close this due to inactivity
