### ISSUE TITLE
undefined local variable or method `__dir__' for Asciidoctor:Module

### ISSUE THREAD

**Issue by MehrCurry** [arc42/arc42-generator#32]
I followed the manual installation process as described in the README.adoc.

In Step 4 i will get multiple errors for the `generateDocbook` step for all sources.

Mac OS 10.15.3. Tried both Java 8 and Java 11.

```
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':/build/src_gen/EN/asciidoc/with-help/:generateDocbook'.
> (NameError) undefined local variable or method `__dir__' for Asciidoctor:Module

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':/build/src_gen/DE/asciidoc/with-help/:generateDocbook'.
> (NameError) undefined local variable or method `__dir__' for Asciidoctor:Module

```

**Comment by gernotstarke** [comment]
@rdmueller thanx for caring about this issue.

**Comment by rdmueller** [comment]
that is quite intereseting.
May I ask why you need to execute the code? All output can be found at github.com/arc42/arc42-template/tree/master/dist

I guess it will take a bit longer to fix the problem...

**Comment by gernotstarke** [comment]
@MehrCurry - is this still an issue, or can we close this issue?

**Comment by gernotstarke** [comment]
I close this, due to inactivity. The generator itself works in general, the Gitpod option is useful for those who encounter issues on their own command line...
