### ISSUE TITLE
Feature request: Tiddlywiki target

### ISSUE THREAD

**Issue by timoc** [arc42/arc42-generator#33]
Tiddlywiki is a wiki implemented as a single HTML file:
https://tiddlywiki.com/

This would be a perfect generator target for self contained "portable"  documentation. Useful for local/offline reference material. Potentially buildable for separate stakeholders.

**Comment by rdmueller** [comment]
I've moved the issues over here to the generator because this is where it belongs :-)

@timoc : if you want to give it a try, take a look at https://github.com/arc42/arc42-generator/blob/master/subBuild.gradle - this is where the main template is converted to other formats.

Maybe you can try to create a tasks which converts one of the other format to tiddly wiki.

**Comment by timoc** [comment]
Here is the basic research to get started. 
> First download an empty wiki from here:https://tiddlywiki.com/

Examine the file and look for this : from the tidlywiki development mailing list.
> You’d need some way to convert the data to individual tiddlers, and then to splice them into the empty HTML file. 
> 
> (Look for the marker <div id="storeArea" style="display:none;”> for the place to split the file). You can see the format for the tiddlers by examining the source of a TiddlyWiki file; 
>
> the only subtlety is that all the text must be HTML encoded.

**Comment by rdmueller** [comment]
ok, HTML encoding shouldn't be a problem.
I've also found the marker.

Shall we create 12 tiddlers - one for each chapter and one overview?

**Comment by timoc** [comment]
Seems reasonable.

**Comment by gernotstarke** [comment]
is this still active?
is there any more interest in creating this format?

(otherwise I suggest to close the issue due to other priorities)

**Comment by timoc** [comment]
I have had to shelve my arc42 work for the moment, so if you can create a quick status write-up and close? i can pick it up if/when i get time.

**Comment by rdmueller** [comment]
quick status: I also had no time to work on this :-|
I'll close it for now
