### ISSUE TITLE
"." in generated docx after arc42-help role 

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-generator#34]
example:

![image](https://user-images.githubusercontent.com/1233990/88407647-b1eac200-cdd2-11ea-9454-06dac4c34b73.png)

this "." is NOT contained in asciidoc source, somehow gets added in generation.

**Comment by rdmueller** [comment]
thanx. I will fix this asap

**Comment by rdmueller** [comment]
where did you get this template from? How can I reproduce the problem?

I just checked the generator and the output seems to be fine.
I then downloaded the german template from the website and opened it in intellij:

![image](https://user-images.githubusercontent.com/1856308/88433361-31da5180-cdfe-11ea-8320-79fed079c5aa.png)

everything is fine.

**Comment by rdmueller** [comment]
ah! sorry, I didn't see you mentioned docx...

**Comment by rdmueller** [comment]
side note: the gitpod container was set to version :latest . This caused the current build to break.
I now set it to a fixed version and downgreaded java 11 to java 8 to make everything run again.

**Comment by rdmueller** [comment]
DOCX files are generated from docBook files. The docBook file looks good:

```xml
<section id="_aufgabenstellung">
<title>Aufgabenstellung</title>
<sidebar role="arc42help">
<formalpara>
<title>Inhalt</title>
<para>Kurzbeschreibung der fachlichen Aufgabenstellung, treibenden Kräfte, Extrakt (oder Abstract) der Anforderungen.
Verweis auf (hoffentlich vorliegende) Anforderungsdokumente (mit Versionsbezeichnungen und Ablageorten).</para>
</formalpara>
```

**Comment by rdmueller** [comment]
the pandoc version used was quite old, so I updated it to 2.10 . Same results. It seems that pandoc adds the dot. Might have to do with the `<formalpara>` tag...

**Comment by rdmueller** [comment]
this seems to be the code in pandoc which adds the dot `. `
https://github.com/jgm/pandoc/blob/ee2e769cd7ee075876c974f94817e6eee294bedd/src/Text/Pandoc/Readers/DocBook.hs#L640

I'll open an issue now

**Comment by rdmueller** [comment]
So, this seems to be a problem with all out pandoc conversions. 
I guess we can create a workaround by turning the paragraph titles (`.tile`) into descrete headlines

```
[descrete]
==== title
```

I'll give this a try tomorrow.

**Comment by rdmueller** [comment]
So, this seems to be a `won't fix` for pandoc. So, we have to go for the workaround.

**Comment by rdmueller** [comment]
great news! PR on pandoc has been merged. As soon as there is a new build of pandoc, we can recreate the templates!

**Comment by rdmueller** [comment]
upgrade of pandoc solved this issue
