### ISSUE TITLE
LaTeX - German Template - thinspace unicode issue

### ISSUE THREAD

**Issue by bjoern-thalheim** [arc42/arc42-generator#35]
I have just drawn the german LaTeX arc42 Template (https://raw.githubusercontent.com/arc42/arc42-template/master/dist/arc42-template-DE-withhelp-latex.zip).
Compiling it gives me the following error:
        ! Package inputenc Error: Unicode character   (U+2009)
        (inputenc)                not set up for use with LaTeX.
This seems to be the same issue mentioned here: https://tex.stackexchange.com/questions/438214/package-inputenc-error-unicode-char-%c3%a2%e2%82%ac-u2009-thin-space

The problem seem to be lines 787 and 1021 containing in total four " --- ".
The spaces around the dashes are thinspaces (unicode character 2009). I found all of them by using \DeclareUnicodeCharacter{2009}{FIXME} in the document preemble.
After replacing the thinspaces with normal spaces everything worked fine.

I produced the error on Windows with TeXworks and MiKTeX 2.9.
It is possible, that this is an issue with only this specific toolchain.

Best regards!

**Comment by rdmueller** [comment]
ok. moved this issue.
I think https://github.com/arc42/arc42-generator/blob/master/subBuild.gradle#L132 is the place where we can add something like

```
doLast {
  def template = new File(localBuildDir.docbook+'/arc42-template.xml')
  template.write(template.text.replaceAll('<where to insert>', '<what to inser>')
}
```
that could fix the generated files

**Comment by bjoern-thalheim** [comment]
Do I understand you correctly? You would like to replace the thinspace character in the original arc42-template.xml before the pandoc transformation into LaTeX?
If yes, I agree that a simple replaceAll of all thinspace \u2009 for a normal space \u2000 probably would solve the problem. We can easily test that.

**Comment by rdmueller** [comment]
good point. I wasn't aware that my dummy code works on the docbook output. I could also work on the final latex output. So up to you - what do you think, where should we replace somethng?

**Comment by bjoern-thalheim** [comment]
IMO it would be best to go for the root cause: so I would replace the thinspace in the docbook output before using pandoc. My standpoint is that such exotic Characters like unicode thinspace have no place in markup source files (but only in the output files).
Unfortunately, I could not get the arc42-generator quickly going to recheck the docbook output. But I'll happily recheck the LaTeX output when available.

**Comment by rdmueller** [comment]
btw: have you already checked if the thin-space is part of the original asciidoc file?

**Comment by bjoern-thalheim** [comment]
Actually, unfortunately not. I'm having problems with the  ./gradlew arc42 command, both locally ("Could not initialize class org.jruby.RubyInstanceConfig") and with gitpod ("Execution failed for task ':/build/src_gen/DE/asciidoc/plain/:generateDocbook'. > java.lang.ExceptionInInitializerError (no error message"). Which file would I be looking for? arc42-generator/build/DE/asciidoc/with-help? (I could see the plain arc42-template.adoc, but unfortunately not the with-help version (that folder is empty).

**Comment by bjoern-thalheim** [comment]
OK, I found the first of the two occurences in the arc42-generator/arc42-template/DE/asciidoc/src/08_concepts.adoc
"* prinzipielle -- meist technische -- Festlegungen übergreifender Art,"
Is it possible that pandoc converts a \u2000--\u2000 from the adoc into a \u2009---\u2009 in the LaTeX file?
If yes, the issue would have to be fixed in the LaTeX target file ...

**Comment by rdmueller** [comment]
I think it worked - the thin space is now replaced with a normal space and this version is already available through the download page. Can you please give it a try?

**Comment by bjoern-thalheim** [comment]
I can confirm that fix works.

The thinspace characters are gone both from the russian and german withhelp templates (tried it in gitpod and Overleaf).
