### ISSUE TITLE
Missing usage of T2A encoding in fontenc package in the russian LaTeX template

### ISSUE THREAD

**Issue by bjoern-thalheim** [arc42/arc42-generator#37]
The russian LaTeX template does not compile as it contains characters which are not in the T1 encoding. Support for Cyrillic alphabet in LaTeX is provided via T2A font encoding.
The allowed encodings can be provided as a parameter in the options of the fontenc package (all of the LaTeX templates use \usepackage[T1]{fontenc}).

You can see the issue and the solution in https://de.overleaf.com/read/mppkhpcvyjzj (arc42-template-withhelp-RU-withT2AFontenc.tex, arc42-template-withhelp-RU-withoutT2AFontenc.tex)

You can get the russian template correctly like this:
```
$ diff arc42-template-withhelp-RU.tex arc42-template-withhelp-RU-fixed.tex
11c11
<   \usepackage[T1]{fontenc}
---
>   \usepackage[T1,T2A]{fontenc}
```

I'm not sure how the solution would look like. 
Pandoc can be provided a parameter, that the russian templates need the T2A encoding support (looks easy: -V fontenc=T2A, see https://stackoverflow.com/questions/18178084/pandoc-and-foreign-characters). The harder part would be that you now have to differentiate between conversion of the russian and the other tempates (I would not like to do this in the gradle file). Maybe this should be done anyway as this would be the way to support also greek, chinese etc. encodings once they are needed.
Alternative (and my favorite): Of course, we could allow T2A encoding in all templates (as it does not hurt the other languages). **We would just provide pandoc with the parameter "-V fontenc=T1,T2A".** That should do the job as long as you are ok with supporting cyrillic encoding in all languages.

**Comment by rdmueller** [comment]
so, adding "-V fontenc=T1,T2A" should be enough?
I will give it a try...

**Comment by bjoern-thalheim** [comment]
I had no luck trying it (locally, maybe my missing luck was my own fault):
`$ git diff
diff --git a/arc42-template b/arc42-template
index ccd9bb6..aa5313d 160000
--- a/arc42-template
+++ b/arc42-template
@@ -1 +1 @@
-Subproject commit ccd9bb623b0befeabe84867550e76ed111e21ee0
+Subproject commit aa5313dad1c24746acfe8fcb4433d68021d85723-dirty
diff --git a/subBuild.gradle b/subBuild.gradle
index ae5b14e..db871b6 100644
--- a/subBuild.gradle
+++ b/subBuild.gradle
@@ -137,6 +137,7 @@ task convert2Latex (
     args = ['-r','docbook',
         '-s',
         '-t','latex',
+       '-V','T1,T2A',
         '-o',localBuildDir.latex+'/arc42-template-'+language+'.tex',
         localBuildDir.docbook+'/arc42-template.xml']
`
The russian template with help did still only have the T1 encoding declared.
Maybe you'll have more luck - I will happily re-test.

**Comment by rdmueller** [comment]
I think it worked. Please check the results an dupdate the ticket :-)
Happy Easter Holidays!

**Comment by bjoern-thalheim** [comment]
Re-Tested it on Overleaf: https://de.overleaf.com/read/mppkhpcvyjzj
I can confirm that works! Thanks.
