### ISSUE TITLE
gitpod build fails

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-generator#39]
AILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'arc42-generator'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.asciidoctor:asciidoctor-gradle-plugin:0.7.0.
     Required by:
         project :
      > Could not resolve org.asciidoctor:asciidoctor-gradle-plugin:0.7.0.
         > Could not get resource 'http://dl.bintray.com/content/aalmiray/asciidoctor/org/asciidoctor/asciidoctor-gradle-plugin/0.7.0/asciidoctor-gradle-plugin-0.7.0.pom'.
            > Could not GET 'http://dl.bintray.com/content/aalmiray/asciidoctor/org/asciidoctor/asciidoctor-gradle-plugin/0.7.0/asciidoctor-gradle-plugin-0.7.0.pom'. Received status code 502 from server: Bad Gateway

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by rdmueller** [comment]
Problem seems to be the old bintray reference. Should be easy to fix.

**Comment by gernotstarke** [comment]
you're the best!
