### ISSUE TITLE
filenames of generated files shall contain LANGUAGE ID

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-generator#4]
I assume that this would have to be done in subBuild.gradle.

But: I'm currently unsure how/if we have the LANG available...

the current line (i.e. 144):

            '-o',localBuildDir.docx+'/arc42-template.docx',

the new version should read something like:

            '-o',localBuildDir.docx+'/arc42-template-`'+$LANG+'.docx',

**Comment by rdmueller** [comment]
applied your suggestion to all derived files.

But the structure of the asciidoc zip is flat and contains no language. will try to fix this tomorrow.

**Comment by gernotstarke** [comment]
that's perfect!

even for asciidoc - the LANG is contained in the directory-name, that's sufficient.
