### ISSUE TITLE
simplify build: ONE gradle task should be sufficient

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42-generator#8]
the ideal solution would be that all available tasks appear initially in
  
    gradle tasks

Then, a

    gradle createDist

should be sufficient to do everything.

**Comment by rdmueller** [comment]
hm. The current behaviour is due to a special feature:
the cTFGM-Tasks analyses the template structure and generates sub build according to it. So, if you create a new folder for a language, the current build will notice it.

But I already have a workaround in mind... I'll keep you updated...

**Comment by rdmueller** [comment]
workaround does not work :-(

Problem is: cTFGM creates subBuild.gradle which is needed to run arc42 task :-(

**Comment by gernotstarke** [comment]
ok, let's close this one.
